name: Testing
on:
  - push
  - pull_request
jobs:
  testing:
    name: Go testing
    runs-on: ubuntu-18.04
    services:
      h2server:
        image: jmrobles/h2:1.4.200
        ports:
          - 9092:9092
        env:
          H2_OPTIONS: -ifNotExists
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.4' 
      - run: go test